// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplIMZBSPijPneVdI1yT9wB47-TqmHuFk',
    appId: '1:592595644296:web:73865b066178b16eff543d',
    messagingSenderId: '592595644296',
    projectId: 'vandad-projec',
    authDomain: 'vandad-projec.firebaseapp.com',
    storageBucket: 'vandad-projec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYB8tSqEtYbMP54EKW4AquVTDFZBoMXfM',
    appId: '1:592595644296:android:a42b7fbadfe9c694ff543d',
    messagingSenderId: '592595644296',
    projectId: 'vandad-projec',
    storageBucket: 'vandad-projec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGr5OSauFdYQo4N-BapJYYBsTi1C2oKOw',
    appId: '1:592595644296:ios:41efe2f20384d324ff543d',
    messagingSenderId: '592595644296',
    projectId: 'vandad-projec',
    storageBucket: 'vandad-projec.appspot.com',
    iosClientId: '592595644296-9moib4irjumh7o0qng6g5k8ji7c0pmjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vandadLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGr5OSauFdYQo4N-BapJYYBsTi1C2oKOw',
    appId: '1:592595644296:ios:41efe2f20384d324ff543d',
    messagingSenderId: '592595644296',
    projectId: 'vandad-projec',
    storageBucket: 'vandad-projec.appspot.com',
    iosClientId: '592595644296-9moib4irjumh7o0qng6g5k8ji7c0pmjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vandadLogin',
  );
}
